#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-010200
#Severity: medium
#Description: Setting the minimum password age protects against users cycling back to a favorite password after satisfying the password reuse requirement.
#Rule Title: Users must not be able to change passwords more than once every 24 hours.
#Version: RHEL-07-010200

#Check Content: To check the minimum password age, run the command: 

#$ grep PASS_MIN_DAYS /etc/login.defs

#The DoD requirement is 1. 
#If it is not set to the required value, this is a finding.


#Fix Text: To specify password minimum age for new accounts, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately: 

#PASS_MIN_DAYS [DAYS]

#A value of 1 day is considered sufficient for many environments. The DoD requirement is 1.

if grep ^PASS_MIN_DAYS /etc/login.defs|grep -v 'Minimum acceptable password length'|grep 1 ; then
echo "This machine is RHEL-07-010200 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010200 Compliant"
else
echo "This machine isn't RHEL-07-010200 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010200 Compliant"
	if grep -r "PASS_MIN_DAYS" /etc/login.defs; then
        sed -i 's/PASS_MIN_DAYS.*0/PASS_MIN_DAYS 1/g' /etc/login.defs
        sed -i 's@#PASS_MIN_DAYS.*@PASS_MIN_DAYS 1@g' /etc/login.defs
        else
	echo "PASS_MIN_DAYS 1" >> /etc/login.defs
	echo "PASS_MIN_DAYS 1" 
        fi
fi



