#!/bin/bash
# RHEL-07-010120
# grep ocredit /etc/security/pwquality.conf
# ocredit = -1
# Note: The value to require a number of lower-case characters to be set is expressed as a negative number in /etc/security/pwquality.conf. 
# Check the value for "ocredit" in /etc/security/pwquality.conf 

if grep ocredit /etc/security/pwquality.conf|grep 1|grep -v '^#'; then
echo "This machine is RHEL-07-010120 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010120 Compliant"
else
echo "This machine isn't RHEL-07-010120 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010120 Compliant"
	if grep -r "ocredit" /etc/security/pwquality.conf; then
        sed -i 's/.*ocredit.*/ocredit = -1/g' /etc/security/pwquality.conf
        sed -i 's@# ocredit.*@ocredit = -1@g' /etc/security/pwquality.conf
        else
	echo "ocredit = -1" >> /etc/security/pwquality.conf
        fi
	
fi

