#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-06-000356
#Severity: medium
#Description: Locking out user accounts after a number of incorrect attempts prevents direct password guessing attacks. Ensuring that an administrator is involved in unlocking locked accounts draws appropriate attention to such situations.
#Rule Title: The system must require administrator action to unlock an account locked by excessive failed login attempts.
#Version: RHEL-06-000356

#auth [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900
#auth required pam_faillock.so authsucc deny=3 unlock_time=604800  fail_interval=900
#Note that any updates made to "/etc/pam.d/password-auth" will be overwritten by the "authconfig" program.  The "authconfig" program should not be used.

if grep pam_faillock.so /etc/pam.d/password-auth; then
echo "This machine is RHEL-07-010371 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010371 Compliant"
else
echo "This machine isn't RHEL-07-010371 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010371 Compliant"
sed -i '/pam_unix.so try_first_pass/i \auth\trequired\t pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900' /etc/pam.d/password-auth
sed -i '/pam_unix.so try_first_pass/a \auth [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900' /etc/pam.d/password-auth
fi

