#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-010180
#Severity: medium
#Description: Using a stronger hashing algorithm makes password cracking attacks more difficult.
#Rule Title: The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes (login.defs).
#Version: RHEL-07-010180

#Check Content: Inspect "/etc/login.defs" and ensure the following line appears: 

#ENCRYPT_METHOD SHA512
#If it does not, this is a finding.
#Fix Text: In "/etc/login.defs", add or correct the following line to ensure the system will use SHA-512 as the hashing algorithm: 
#ENCRYPT_METHOD SHA512

if grep "ENCRYPT_METHOD" /etc/login.defs | grep SHA512; then
echo "This machine is RHEL-07-010180 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010180 Compliant"
else
echo "This machine isn't RHEL-07-010180 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010180 Compliant"
echo "ENCRYPT_METHOD SHA512" >> /etc/login.defs
fi
