#!/bin/bash
# RHEL-07-010160
# grep maxclassrepeat /etc/security/pwquality.conf
# maxclassrepeat = 4
# Note: The value to require a number of lower-case characters to be set is expressed as 4 in /etc/security/pwquality.conf. 
# Check the value for "maxclassrepeat" in /etc/security/pwquality.conf 

if grep maxclassrepeat /etc/security/pwquality.conf|grep 4|grep -v '^#'; then
echo "This machine is RHEL-07-010160 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010160 Compliant"
else
echo "This machine isn't RHEL-07-010160 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010160 Compliant"
	if grep -r "maxclassrepeat" /etc/security/pwquality.conf; then
        sed -i 's/.*maxclassrepeat.*/maxclassrepeat = 4/g' /etc/security/pwquality.conf
        sed -i 's@# maxclassrepeat.*@maxclassrepeat = 4@g' /etc/security/pwquality.conf
        else
	echo "maxclassrepeat = 4" >> /etc/security/pwquality.conf
        fi
	
fi

