#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-010441
#Severity: low
#Rule Title: The SSH daemon must not allow override.
#Version: RHEL-07-010441

#Check Content: To ensure users are not able to present environment daemons, run the following command: 
# grep PermitUserEnvironment /etc/ssh/sshd_config
#PermitUserEnvironment no

if grep PermitUserEnvironment /etc/ssh/sshd_config|grep -v '^#'|grep no; then
echo "This machine is RHEL-06-000242 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000242 Compliant"
else
echo "This machine isn't RHEL-06-000242 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000242 Compliant"
sed -i 's/#PermitUserEnvironment.*/PermitUserEnvironment no/g' /etc/ssh/sshd_config
#/etc/init.d/sshd restart
fi
