#!/bin/bash
#Created by Matthew M. Conley / SimonTek
#Version: RHEL-07-020000
#Severity: high
#Description: The "rsh-server" package provides several obsolete and insecure network services. Removing it decreases the risk of those services' accidental (or intentional) activation.
#Rule Title: The rsh-server package must not be installed.
#Version: RHEL-07-020000

# rpm -q rsh-server
#If the package is installed, this is a finding.
#Fix Text: The "rsh-server" package can be uninstalled with the following command: 

if rpm -qa |grep rsh-server; then
echo "This machine isn't RHEL-07-020000 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-020000 Compliant"
yum erase rsh-server -y
else
echo "This machine is RHEL-07-020000 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-020000 Compliant"
fi
