#!/bin/bash
#Created by Matthew M. Conley / SimonTek
#Version: RHEL-07-021910
#Severity: low
#Rule Title: Remove telnet-server
#Version: RHEL-07-021910

#Check Content: Run the following command to determine if the "telnet-server" package is installed: 

if rpm -q telnet-server|grep "not installed"; then
echo "This machine is RHEL-07-021910 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-021910 Compliant"
else
echo "This machine isn't RHEL-07-021910 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-021910 Compliant"
yum remove telnet-server -y
fi
