#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-010190
#Severity: medium
#Description: Using a stronger hashing algorithm makes password cracking attacks more difficult.
#Rule Title: The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes (libuser.conf).
#Version: RHEL-07-010190

#Check Content: Inspect "/etc/libuser.conf" and ensure the following line appears in the "[default]" section: 
#crypt_style = sha512
#If it does not, this is a finding.
#Fix Text: In "/etc/libuser.conf", add or correct the following line in its "[defaults]" section to ensure the system will use the SHA-512 algorithm for password hashing: 
#crypt_style = sha512

if grep crypt_style /etc/libuser.conf|grep "sha512"; then
echo "This machine is RHEL-07-010190 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010190 Compliant"
else
echo "This machine isn't RHEL-07-010190 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010190 Compliant"
	if grep -r "crypt_style" /etc/libuser.conf; then
        sed -i 's/.*crypt_style.*/crypt_style = sha512/g' /etc/libuser.conf
        sed -i 's@#crypt_style.*@crypt_style = sha512@g' /etc/libuser.conf
        else
	echo "crypt_style = sha512" >> /etc/libuser.conf
        fi
fi
