#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-040860
#Severity: medium
#Rule Title: The system must not forward IPv6 source-routed packets
#Version: RHEL-07-040860

#Check Content: The status of the "net.ipv6.conf.all.accept_source_route" kernel parameter can be queried by running the following command: 
#$ sysctl net.ipv6.conf.all.accept_source_route
#The output of the command should indicate a value of "0". 
#If the correct value is not returned, this is a finding.

#Fix Text: To set the runtime status of the "net.ipv6.conf.all.accept_source_route" kernel parameter, run the following command: 
# sysctl -w net.ipv6.conf.all.accept_source_route=0
#net.ipv6.conf.all.accept_source_route = 0

if grep ^net.ipv6.conf.all.accept_source_route /etc/sysctl.conf|grep 0; then
echo "This machine is RHEL-07-040860 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-040860 Compliant"
else
echo "This machine isn't RHEL-07-040860 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-040860 Compliant"
if grep --silent ^net.ipv6.conf.all.accept_source_route /etc/sysctl.conf ; then
	sed -i 's/^net.ipv6.conf.all.accept_source_route.*/net.ipv6.conf.all.accept_source_route = 0/g' /etc/sysctl.conf
else
	echo "" >> /etc/sysctl.conf
	echo "# Ignore ipv6 packets" >> /etc/sysctl.conf
	echo "net.ipv6.conf.all.accept_source_route = 0" >> /etc/sysctl.conf
	/sbin/sysctl -w net.ipv6.conf.all.accept_source_route=0 
fi
fi
