#!/bin/bash
# RHEL-07-010073
# idle-activation-enabled /etc/dconf/db/local.d/*
# idle-activation-enabled=true 

if grep idle-activation-enabled /etc/dconf/db/local.d/00-screensaver |grep true; then
echo "This machine is RHEL-07-010073 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010073 Compliant"
else
echo "This machine isn't RHEL-07-010073 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010073 Compliant"
	if grep -r "idle-activation-enabled" /etc/dconf/db/local.d/; then
        sed -i 's/idle-activation-enabled.*/idle-activation-enabled true/g'/etc/dconf/db/local.d/00-screensaver
        sed -i 's@#idle-activation-enabled.*@idle-activation-enabled true@g' /etc/dconf/db/local.d/00-screensaver
        else
	echo "idle-activation-enabled=true " >> /etc/dconf/db/local.d/00-screensaver
        fi
fi
