#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-010420
#Severity: medium
#Description: Setting the minimum password age protects against users cycling back to a favorite password after satisfying the password reuse requirement.
#Rule Title: The delay between logon prompts following a failed console logon attempt must be at least four seconds
#Version: RHEL-07-010420

#$ grep FAIL_DELAY /etc/login.defs
#If it is not set to the required value, this is a finding.
#Fix Text: To specify password minimum age for new accounts, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately: 
#FAIL_DELAY [4]
#A value of 4 day is considered sufficient for many environments. The DoD requirement is 4.

if grep ^FAIL_DELAY /etc/login.defs|grep -v 'Maximum number of days'|grep 4 ; then
echo "This machine is RHEL-07-010420 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010420 Compliant"
else
echo "This machine isn't RHEL-07-010420 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010420 Compliant"
	if grep -r "FAIL_DELAY" /etc/login.defs; then
        sed -i 's/FAIL_DELAY.*99/FAIL_DELAY 4/g' /etc/login.defs
        sed -i 's@#FAIL_DELAY.*@FAIL_DELAY 4@g' /etc/login.defs
        else
	echo "FAIL_DELAY 4" >> /etc/login.defs
	echo "FAIL_DELAY 4" 
        fi
fi
