#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Version: RHEL-07-010220
#Severity: medium
#Description: Setting the minimum password age protects against users cycling back to a favorite password after satisfying the password reuse requirement.
#Rule Title: Users must not be able to change passwords more than once every 24 hours.
#Version: RHEL-07-010220

#$ grep PASS_MAX_DAYS /etc/login.defs
#If it is not set to the required value, this is a finding.
#Fix Text: To specify password minimum age for new accounts, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately: 
#PASS_MAX_DAYS [60]
#A value of 60 day is considered sufficient for many environments. The DoD requirement is 60.

if grep ^PASS_MAX_DAYS /etc/login.defs|grep -v 'Maximum number of days'|grep 60 ; then
echo "This machine is RHEL-07-010220 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010220 Compliant"
else
echo "This machine isn't RHEL-07-010220 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010220 Compliant"
	if grep -r "PASS_MAX_DAYS" /etc/login.defs; then
        sed -i 's/PASS_MAX_DAYS.*99/PASS_MAX_DAYS 60/g' /etc/login.defs
        sed -i 's@#PASS_MAX_DAYS.*@PASS_MAX_DAYS 60@g' /etc/login.defs
        else
	echo "PASS_MAX_DAYS 60" >> /etc/login.defs
	echo "PASS_MAX_DAYS 60" 
        fi
fi
