#!/bin/bash
# RHEL-07-010090
# grep ucredit /etc/security/pwquality.conf
# ucredit = -1
# Note: The value to require a number of lower-case characters to be set is expressed as a negative number in /etc/security/pwquality.conf. 
# Check the value for "ucredit" in /etc/security/pwquality.conf 

if grep ucredit /etc/security/pwquality.conf|grep 1|grep -v '^#'; then
echo "This machine is RHEL-07-010090 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010090 Compliant"
else
echo "This machine isn't RHEL-07-010090 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010090 Compliant"
	if grep -r "ucredit" /etc/security/pwquality.conf; then
        sed -i 's/.*ucredit.*/ucredit = -1/g' /etc/security/pwquality.conf
        sed -i 's@# ucredit.*@ucredit = -1@g' /etc/security/pwquality.conf
        else
	echo "ucredit = -1" >> /etc/security/pwquality.conf
        fi
	
fi

