#!/bin/bash
# Rule Title: The operating system must prohibit the use of cached nss authenticators after one day.
# STIG ID:	RHEL-07-010402
# Rule ID:	RHEL-07-010402_rule
# Vuln ID:	RHEL-07-010402
# Severity:	CAT II


