#!/bin/bash
# RHEL-07-010150
# grep maxrepeat /etc/security/pwquality.conf
# maxrepeat = 2
# Note: The value to require a number of lower-case characters to be set is expressed as 2 in /etc/security/pwquality.conf. 
# Check the value for "maxrepeat" in /etc/security/pwquality.conf 

if grep maxrepeat /etc/security/pwquality.conf|grep 2|grep -v '^#'; then
echo "This machine is RHEL-07-010150 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010150 Compliant"
else
echo "This machine isn't RHEL-07-010150 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010150 Compliant"
	if grep -r "maxrepeat" /etc/security/pwquality.conf; then
        sed -i 's/.*maxrepeat.*/maxrepeat = 2/g' /etc/security/pwquality.conf
        sed -i 's@# maxrepeat.*@maxrepeat = 2@g' /etc/security/pwquality.conf
        else
	echo "maxrepeat = 2" >> /etc/security/pwquality.conf
        fi
	
fi

