#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: RHEL-07-010170
#Version: RHEL-07-010170
#Severity: medium
#Description: Using a stronger hashing algorithm makes password cracking attacks more difficult.
#Rule Title: The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes (system-auth).
#Version: RHEL-07-010170

#Check Content: Inspect the "password" section of "/etc/pam.d/system-auth" and ensure that the "pam_unix.so" module includes the argument "sha512".
#$ grep sha512 /etc/pam.d/system-auth" 
#If it does not, this is a finding.
#Fix Text: In "/etc/pam.d/system-auth", the "password" section of the file controls which PAM modules execute during a password change. Set the "pam_unix.so" module in the "password" section to include the argument "sha512", as shown below: 

#password sufficient pam_unix.so sha512 [other arguments...]

if grep sha512 /etc/pam.d/system-auth|grep password|grep sufficient; then
echo "This machine is RHEL-07-010170 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010170 Compliant"
else
echo "This machine isn't RHEL-07-010170 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010170 Compliant"
sed -i '/^password    sufficient/ s/$/ sha512/' /etc/pam.d/system-auth
fi
