#!/bin/bash
# RHEL-07-010100
# grep lcredit /etc/security/pwquality.conf
# lcredit = -1
# Note: The value to require a number of lower-case characters to be set is expressed as a negative number in /etc/security/pwquality.conf. 
# Check the value for "lcredit" in /etc/security/pwquality.conf 

if grep lcredit /etc/security/pwquality.conf|grep 1|grep -v '^#'; then
echo "This machine is RHEL-07-010100 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-010100 Compliant"
else
echo "This machine isn't RHEL-07-010100 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-010100 Compliant"
	if grep -r "lcredit" /etc/security/pwquality.conf; then
        sed -i 's/.*lcredit.*/lcredit = -1/g' /etc/security/pwquality.conf
        sed -i 's@# lcredit.*@lcredit = -1@g' /etc/security/pwquality.conf
        else
	echo "lcredit = -1" >> /etc/security/pwquality.conf
        fi
	
fi

