#!/bin/bash
#Created by Matthew M. Conley / SimonTek
#Version: RHEL-07-020150
#Severity: medium
#Description: Ensuring the validity of packages' cryptographic signatures prior to installation ensures the provenance of the software and protects against malicious tampering.
#Rule Title: The system package management tool must cryptographically verify the authenticity of system software packages during installation.

#Check Content: To determine whether "yum" is configured to use "gpgcheck", inspect "/etc/yum.conf" and ensure the following appears in the "[main]" section: 
#gpgcheck=1
#If GPG checking is not enabled, this is a finding.
#gpgcheck=1

if grep "gpgcheck" /etc/yum.conf|grep 1; then
echo "This machine is RHEL-07-020150 Compliant" >> /var/log/Stig
echo "This machine is RHEL-07-020150 Compliant"
else
echo "This machine isn't RHEL-07-020150 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-07-020150 Compliant"
sed -i 's@gpgcheck=0@gpgcheck=1@g' /etc/yum.conf
fi
